[package]
name = "wimage"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", default-features = false }
png = "0.18.0"
zstd = { version = "0.13.3", default-features = false }
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
zstd = { version = "0.13.3", default-features = false, features = ["fat-lto"] }

[dev-dependencies]
criterion = { version = "0.5" }

[[bench]]
name = "imageprocessing_diff"
harness = false

[[bench]]
name = "index_from_rgba"
harness = false
